[package]
name = "amethyst_core"
version = "0.10.1"
authors = ["Simon Rönnberg <seamonr@gmail.com>", "Joël Lupien <jojolepro@jojolepro.com>", "Amethyst Foundation <contact@amethyst.rs>"]
edition = "2018"
description = "Amethyst core"

documentation = "https://docs.amethyst.rs/stable/amethyst_core/"
homepage = "https://amethyst.rs/"
repository = "https://github.com/amethyst/amethyst"

license = "MIT/Apache-2.0"

[badges]
travis-ci = { repository = "amethyst/amethyst" }

[dependencies]
nalgebra = { version = "0.19.0", features = ["serde-serialize", "mint"] }
alga = { version = "0.9.2", default-features = false }
alga_derive = "0.9.1"
approx = "0.3.2"
amethyst_error = { path = "../amethyst_error", version = "0.5.0" }
fnv = "1.0.6"
log = "0.4.8"
num-traits = "0.2.11"
rayon = "1.3.0"
serde = { version = "1", features = ["derive"] }
getset = "0.1"
derive-new = "0.5.8"
smallvec = "1.4"
shrinkwraprs = "0.3"
shrev = "1.1"
derivative = "2.1.1"

thread_profiler = { version = "0.3", optional = true }

[dependencies.legion]
git = "https://github.com/TomGillen/legion"
rev = "b93b636d"
default-features = false
features = ["serialize", "crossbeam-events", "codegen"]

[dev-dependencies]
#amethyst = { path = "..", version = "0.15.1" }
ron = "0.5.1"

[features]
profiler = ["thread_profiler/thread_profiler"]
parallel = ["legion/parallel"]
